// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: user/v1/service_tag.proto

package user

import (
	v1 "github.com/core-pb/tag/tag/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTagRequest) Reset() {
	*x = GetTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagRequest) ProtoMessage() {}

func (x *GetTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagRequest.ProtoReflect.Descriptor instead.
func (*GetTagRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{0}
}

type GetTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type []*v1.Type `protobuf:"bytes,1,rep,name=type,proto3" json:"type,omitempty"`
	Tag  []*v1.Tag  `protobuf:"bytes,2,rep,name=tag,proto3" json:"tag,omitempty"`
}

func (x *GetTagResponse) Reset() {
	*x = GetTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagResponse) ProtoMessage() {}

func (x *GetTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagResponse.ProtoReflect.Descriptor instead.
func (*GetTagResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{1}
}

func (x *GetTagResponse) GetType() []*v1.Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *GetTagResponse) GetTag() []*v1.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type SetTagTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        *uint64          `protobuf:"fixed64,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Info      *structpb.Struct `protobuf:"bytes,2,opt,name=info,proto3,oneof" json:"info,omitempty"`
	Inherit   *bool            `protobuf:"varint,3,opt,name=inherit,proto3,oneof" json:"inherit,omitempty"`
	Exclusive *bool            `protobuf:"varint,4,opt,name=exclusive,proto3,oneof" json:"exclusive,omitempty"`
}

func (x *SetTagTypeRequest) Reset() {
	*x = SetTagTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTagTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagTypeRequest) ProtoMessage() {}

func (x *SetTagTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagTypeRequest.ProtoReflect.Descriptor instead.
func (*SetTagTypeRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{2}
}

func (x *SetTagTypeRequest) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SetTagTypeRequest) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SetTagTypeRequest) GetInherit() bool {
	if x != nil && x.Inherit != nil {
		return *x.Inherit
	}
	return false
}

func (x *SetTagTypeRequest) GetExclusive() bool {
	if x != nil && x.Exclusive != nil {
		return *x.Exclusive
	}
	return false
}

type SetTagTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetTagTypeResponse) Reset() {
	*x = SetTagTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTagTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagTypeResponse) ProtoMessage() {}

func (x *SetTagTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagTypeResponse.ProtoReflect.Descriptor instead.
func (*SetTagTypeResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{3}
}

type DeleteTagTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []uint64 `protobuf:"fixed64,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTagTypeRequest) Reset() {
	*x = DeleteTagTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTagTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagTypeRequest) ProtoMessage() {}

func (x *DeleteTagTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagTypeRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTagTypeRequest) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteTagTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTagTypeResponse) Reset() {
	*x = DeleteTagTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTagTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagTypeResponse) ProtoMessage() {}

func (x *DeleteTagTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagTypeResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagTypeResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{5}
}

type SetTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *uint64          `protobuf:"fixed64,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	TypeId   *uint64          `protobuf:"fixed64,2,opt,name=type_id,json=typeId,proto3,oneof" json:"type_id,omitempty"`
	ParentId *uint64          `protobuf:"fixed64,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Data     *structpb.Struct `protobuf:"bytes,4,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Info     *structpb.Struct `protobuf:"bytes,5,opt,name=info,proto3,oneof" json:"info,omitempty"`
}

func (x *SetTagRequest) Reset() {
	*x = SetTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagRequest) ProtoMessage() {}

func (x *SetTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagRequest.ProtoReflect.Descriptor instead.
func (*SetTagRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{6}
}

func (x *SetTagRequest) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SetTagRequest) GetTypeId() uint64 {
	if x != nil && x.TypeId != nil {
		return *x.TypeId
	}
	return 0
}

func (x *SetTagRequest) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *SetTagRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SetTagRequest) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

type SetTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetTagResponse) Reset() {
	*x = SetTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagResponse) ProtoMessage() {}

func (x *SetTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagResponse.ProtoReflect.Descriptor instead.
func (*SetTagResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{7}
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []uint64 `protobuf:"fixed64,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTagRequest) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{9}
}

type SetUserTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64           `protobuf:"fixed64,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TagId  uint64           `protobuf:"fixed64,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Data   *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SetUserTagRequest) Reset() {
	*x = SetUserTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserTagRequest) ProtoMessage() {}

func (x *SetUserTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserTagRequest.ProtoReflect.Descriptor instead.
func (*SetUserTagRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{10}
}

func (x *SetUserTagRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetUserTagRequest) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *SetUserTagRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetUserTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetUserTagResponse) Reset() {
	*x = SetUserTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserTagResponse) ProtoMessage() {}

func (x *SetUserTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserTagResponse.ProtoReflect.Descriptor instead.
func (*SetUserTagResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{11}
}

type DeleteUserTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"fixed64,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TagId  uint64 `protobuf:"fixed64,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *DeleteUserTagRequest) Reset() {
	*x = DeleteUserTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserTagRequest) ProtoMessage() {}

func (x *DeleteUserTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserTagRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserTagRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteUserTagRequest) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type DeleteUserTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteUserTagResponse) Reset() {
	*x = DeleteUserTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_service_tag_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserTagResponse) ProtoMessage() {}

func (x *DeleteUserTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_service_tag_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserTagResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_service_tag_proto_rawDescGZIP(), []int{13}
}

var File_user_v1_service_tag_proto protoreflect.FileDescriptor

var file_user_v1_service_tag_proto_rawDesc = []byte{
	0x0a, 0x19, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x1a, 0x10, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x61, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x74, 0x61, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x61, 0x67, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x03,
	0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x61, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0xc6, 0x01, 0x0a, 0x11,
	0x53, 0x65, 0x74, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x48, 0x00, 0x52,
	0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x01, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x69, 0x6e, 0x68, 0x65,
	0x72, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x07, 0x69, 0x6e, 0x68,
	0x65, 0x72, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75,
	0x73, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x03, 0x52, 0x09, 0x65, 0x78,
	0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69,
	0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x69,
	0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x65, 0x78, 0x63, 0x6c, 0x75,
	0x73, 0x69, 0x76, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x54, 0x61, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x06, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xfb, 0x01, 0x0a, 0x0d,
	0x53, 0x65, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x1c, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x06, 0x48, 0x01, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x20, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x06, 0x48, 0x02, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x04, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x0a, 0x0a,
	0x08, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x65, 0x74,
	0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x06, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x70, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x06, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x46, 0x0a, 0x14,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x74,
	0x61, 0x67, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xfb, 0x03,
	0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x3b, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x12,
	0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x61,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a,
	0x06, 0x53, 0x65, 0x74, 0x54, 0x61, 0x67, 0x12, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x09, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x12, 0x19, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x47, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x67, 0x12, 0x1a,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x67, 0x12, 0x1d, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x70,
	0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x75,
	0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_v1_service_tag_proto_rawDescOnce sync.Once
	file_user_v1_service_tag_proto_rawDescData = file_user_v1_service_tag_proto_rawDesc
)

func file_user_v1_service_tag_proto_rawDescGZIP() []byte {
	file_user_v1_service_tag_proto_rawDescOnce.Do(func() {
		file_user_v1_service_tag_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_v1_service_tag_proto_rawDescData)
	})
	return file_user_v1_service_tag_proto_rawDescData
}

var file_user_v1_service_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_user_v1_service_tag_proto_goTypes = []any{
	(*GetTagRequest)(nil),         // 0: user.v1.GetTagRequest
	(*GetTagResponse)(nil),        // 1: user.v1.GetTagResponse
	(*SetTagTypeRequest)(nil),     // 2: user.v1.SetTagTypeRequest
	(*SetTagTypeResponse)(nil),    // 3: user.v1.SetTagTypeResponse
	(*DeleteTagTypeRequest)(nil),  // 4: user.v1.DeleteTagTypeRequest
	(*DeleteTagTypeResponse)(nil), // 5: user.v1.DeleteTagTypeResponse
	(*SetTagRequest)(nil),         // 6: user.v1.SetTagRequest
	(*SetTagResponse)(nil),        // 7: user.v1.SetTagResponse
	(*DeleteTagRequest)(nil),      // 8: user.v1.DeleteTagRequest
	(*DeleteTagResponse)(nil),     // 9: user.v1.DeleteTagResponse
	(*SetUserTagRequest)(nil),     // 10: user.v1.SetUserTagRequest
	(*SetUserTagResponse)(nil),    // 11: user.v1.SetUserTagResponse
	(*DeleteUserTagRequest)(nil),  // 12: user.v1.DeleteUserTagRequest
	(*DeleteUserTagResponse)(nil), // 13: user.v1.DeleteUserTagResponse
	(*v1.Type)(nil),               // 14: tag.v1.Type
	(*v1.Tag)(nil),                // 15: tag.v1.Tag
	(*structpb.Struct)(nil),       // 16: google.protobuf.Struct
}
var file_user_v1_service_tag_proto_depIdxs = []int32{
	14, // 0: user.v1.GetTagResponse.type:type_name -> tag.v1.Type
	15, // 1: user.v1.GetTagResponse.tag:type_name -> tag.v1.Tag
	16, // 2: user.v1.SetTagTypeRequest.info:type_name -> google.protobuf.Struct
	16, // 3: user.v1.SetTagRequest.data:type_name -> google.protobuf.Struct
	16, // 4: user.v1.SetTagRequest.info:type_name -> google.protobuf.Struct
	16, // 5: user.v1.SetUserTagRequest.data:type_name -> google.protobuf.Struct
	0,  // 6: user.v1.Tag.GetTag:input_type -> user.v1.GetTagRequest
	2,  // 7: user.v1.Tag.SetTagType:input_type -> user.v1.SetTagTypeRequest
	4,  // 8: user.v1.Tag.DeleteTagType:input_type -> user.v1.DeleteTagTypeRequest
	6,  // 9: user.v1.Tag.SetTag:input_type -> user.v1.SetTagRequest
	8,  // 10: user.v1.Tag.DeleteTag:input_type -> user.v1.DeleteTagRequest
	10, // 11: user.v1.Tag.SetUserTag:input_type -> user.v1.SetUserTagRequest
	12, // 12: user.v1.Tag.DeleteUserTag:input_type -> user.v1.DeleteUserTagRequest
	1,  // 13: user.v1.Tag.GetTag:output_type -> user.v1.GetTagResponse
	3,  // 14: user.v1.Tag.SetTagType:output_type -> user.v1.SetTagTypeResponse
	5,  // 15: user.v1.Tag.DeleteTagType:output_type -> user.v1.DeleteTagTypeResponse
	7,  // 16: user.v1.Tag.SetTag:output_type -> user.v1.SetTagResponse
	9,  // 17: user.v1.Tag.DeleteTag:output_type -> user.v1.DeleteTagResponse
	11, // 18: user.v1.Tag.SetUserTag:output_type -> user.v1.SetUserTagResponse
	13, // 19: user.v1.Tag.DeleteUserTag:output_type -> user.v1.DeleteUserTagResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_user_v1_service_tag_proto_init() }
func file_user_v1_service_tag_proto_init() {
	if File_user_v1_service_tag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_v1_service_tag_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v1_service_tag_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v1_service_tag_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SetTagTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v1_service_tag_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SetTagTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v1_service_tag_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTagTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v1_service_tag_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTagTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v1_service_tag_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SetTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v1_service_tag_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SetTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v1_service_tag_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v1_service_tag_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v1_service_tag_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SetUserTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v1_service_tag_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*SetUserTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v1_service_tag_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteUserTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v1_service_tag_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteUserTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_user_v1_service_tag_proto_msgTypes[2].OneofWrappers = []any{}
	file_user_v1_service_tag_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_v1_service_tag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_service_tag_proto_goTypes,
		DependencyIndexes: file_user_v1_service_tag_proto_depIdxs,
		MessageInfos:      file_user_v1_service_tag_proto_msgTypes,
	}.Build()
	File_user_v1_service_tag_proto = out.File
	file_user_v1_service_tag_proto_rawDesc = nil
	file_user_v1_service_tag_proto_goTypes = nil
	file_user_v1_service_tag_proto_depIdxs = nil
}
