name: Lint
on:
  push:
    branches:
      - '!main'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - run: go version
      - run: diff -u <(echo -n) <(gofmt -d .)

      - uses: bufbuild/buf-action@v1
        with:
          format: false
          lint: true
          breaking: true
          push: false
          archive: false
          pr_comment: false

      - uses: DoozyX/clang-format-lint-action@v0.18.1
        with:
          source: 'pb'
          extensions: 'proto'
          style: '{BasedOnStyle: Google, IndentWidth: 4, AlignConsecutiveDeclarations: true, AlignConsecutiveAssignments: true, ColumnLimit: 0}'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
