name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  buf-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Tags
        run: |
          latest_tag=$(git tag -l "v*" | sort -V | tail -n 1)
          echo "$latest_tag"

          if [ "$latest_tag" == "${{ github.ref_name }}" ]; then
            echo "BUILD_TAG=corepbx/user:${{ github.ref_name }},corepbx/user:latest" >> $GITHUB_ENV
          else
            echo "BUILD_TAG=corepbx/user:${{ github.ref_name }}" >> $GITHUB_ENV
          fi

          echo "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: build/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.BUILD_TAG }}
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            COMMIT_DATE=${{ github.event.head_commit.timestamp }}
            GIT_TAG=${{ github.ref_name }}
