name: Test
on:
  push:
    branches:
      - '!main'
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        version: [1.23, 1.22, 1.21]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}

      - run: go version
      - run: go test ./...
      - run: go test -race ./...
